apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    name: test-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: test-deployment
